- main.go
This is a rework of sarlalian pull request #118.
See https://github.com/42wim/matterircd/pull/118 for original PR that was not mergeable.
> Add -mmskiptlsverify option to skip TLS certificate checks on mmserver.

- main.go
- mm-go-irckit/user.go
By default matterircd doesn't attempt to read any config file, now it
will attempt to read from /usr/local/etc/matterircd/matterircd.toml if
it exists.
> Added a default value for the '-conf' flag

- README.md
- mm-go-irckit/mmservice.go
- mm-go-irckit/mmuser.go
I'd like to configure my IRC client to instruct mattermost when to deidle channels when I open them up. This means I can use the IRC client in conjunction with a web client and they won't fight.
I've tested this both for private message channels, and named channels. It doesn't work on groups, because `GetChannelId` doesn't consistently compute those group names (I'll make a distinct patch for that against `matterbridge`).
> Add UPDATELASTVIEWED command, and make DisableAutoView work consistently

- mm-go-irckit/slackuser.go
This handles some common Slack events. They show up as new messages:
```
10:21:04 < someuser> Such wow
10:28:05 < otheruser> [M 10:21:04] Added reaction :ok_hand:
```
> Add handling of reactions, stars and pins

- config/config.go
- matterircd.toml.example
- mm-go-irckit/mmservice.go
- mm-go-irckit/mmuser.go
Currently matterircd uses Username as the nick handler for every
user, regardless if such user have a Nickname set. There is an inherent
restriction on using the Nickname - they may contain non-ascii chars,
breaking compatibility with IRC clients.
This patch adds the config option PreferNickname - if set, we check
Nickname and if it's not empty and doesn't contain any non-ascii
character, matterircd uses the Nickname instead of Username.
It's a Mattermost-only option for the time being.
Signed-off-by: Guilherme G. Piccoli <gpiccoli@canonical.com>
V2 just uploaded (2020-06-23): instead of checking just for ASCII chars, stick with
IRC RFC and limit the nicknames according to this specification (and to max of 27 chars).
> Add option to use Nickname instead of Username

- main.go
For a single-user bridge, listening on a Unix socket can be more
convenient than listening on a TCP port: you don't have to worry about
port security or port clashes (especially if running on somebody else's
multi-user system), and you can just rely on filesystem permissions on
the socket in question.  Of course you need an IRC client that supports
connecting to Unix sockets, but e.g. irssi does.
If the bind option is given a path (detected by checking whether it
contains the path separator character), treat it as the path to a Unix
socket and bind to that.
> Allow binding to a Unix socket

- config/config.go
- matterircd.toml.example
- mm-go-irckit/mmuser.go
Example with config option enabled:
`|12:26 <hloeung> Testing (re @hloeung)`
So it will only show (re @nick_of_user) without the post message that the reply is made to.
> Add option to disable showing replies/parent posts

- mm-go-irckit/mmuser.go
After running the code with commit 50e16b8624 (that introduced the ability
of using nicks), I've noticed in rare occasions we could face a crash on
topic/system_header change due to invalid nickname. I believe this is related
to other users clearing their nicks after the start of matterircd.
The way I've fixed that was to add some additional checks to system_header
change event, and then was able to run several weeks without crashes
(although the checks were triggered sometimes, preventing the NIL crash).
Notice the Warn was never reached though, but I kept that for safety!
Fixes: 50e16b8624 ["Add option to use Nickname instead of Username (#273)"]
Signed-off-by: Guilherme G. Piccoli <gpiccoli@canonical.com>
> Fix crash on topic change due to invalid user's nickname

- mm-go-irckit/server_commands.go
This is especially useful with multiple users. So if a user tries to
log in, but quits after a failed attempt, other users are not affected.
Fixes #298
> Fix crash on quit without login

- mm-go-irckit/server_commands.go
Get's rid of the extra `p`'s output.
> Fix noise from printing private channel mode (#301)

- bridge/mattermost/mattermost.go
- matterircd.toml.example
- mm-go-irckit/server_commands.go
- mm-go-irckit/userbridge.go
Add support similar to prefixContext but have the message/thread context at the end of the message.
We also want to include the parent posts' user nick so that configured IRC clients would still highlight on replies to a user's reply.
> Support for adding message/thread context at the end

- mm-go-irckit/userbridge.go
Add updateCounterMutex, which should prevent the crash below (the rest of the relevant goroutines can be seen in https://paste.ubuntu.com/p/H4Xy9DZmWs/):
```
fatal error: concurrent map writes
goroutine 43950 [running]:
runtime.throw(0x99b098, 0x15)
/snap/go/6439/src/runtime/panic.go:1116 +0x72 fp=0xc001133d68 sp=0xc001133d38 pc=0x439012
runtime.mapassign_faststr(0x8ec060, 0xc0002554a0, 0xc000c2c380, 0x1a, 0xc00093d8d0)
/snap/go/6439/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc001133dd0 sp=0xc001133d68 pc=0x4162f1
github.com/42wim/matterircd/mm-go-irckit.(*User).updateLastViewed(0xc000144500, 0xc000c2c380, 0x1a)
/home/paul/go/src/github.com/42wim/matterircd/mm-go-irckit/userbridge.go:817 +0xc8 fp=0xc001133e28 sp=0xc001133dd0 pc=0x86b528 …
```
> UserBridge: lock updateCounter against concurrent updates

- bridge/mattermost/mattermost.go
- matterircd.toml.example
This makes busy reply threads on long messages more tolerable, in my brief experience.
The length limit is entirely arbitrary and could be made configurable.
Example:
```
<pjdc> `To build Emacs with xwidgets support, you will need to install
the webkit2gtk-4.0 package; version 2.12 or later is required. (This
change was actually made in Emacs 26.1, but was not called out in its
NEWS.)`
<pjdc> just one more reply test, eh? (re @pjdc: `To build Emacs with ...)
```
> add ShortenReplies

- bridge/mattermost/mattermost.go
- pkg/matterclient/matterclient.go
Clean up antiIdle goroutines when reconnecting in case of network
failures.
> Move antiIdle to matterclient package. Fixes #327

- pkg/matterclient/matterclient.go
Would've also fixed #327, we make sure m.User can't be nil.
> Update user after error checking

- bridge/slack/slack.go
If bot sets the username in the message it was not being used. For example slack-irc bridge uses this.
If message contained only pretext without actual text it was not marked as handled and thus whole details were shown. For example Zendesk ticket notifications sometimes contain only pretext.
> Fix missing botname and fix attachments without text

- .gitignore
- bridge/mattermost/mattermost.go
- mm-go-irckit/server_commands.go
Per https://github.com/42wim/matterircd/pull/320, split out support for replying to older threads using parent/post ID.
10:59 <hloeung> @@epjhhxi3fpd33kb7usmyfuza6r testing replying to old thread
11:00 <hloeung> @@epjhhxi3fpd33kb7usmyfuza6c testing replying to invalid thread
11:00 <hloeung> @@epjhhxi3fpd33kb7usmyfuza6r
11:00 <hloeung> @@epjhhxi3fpd33kb7usmyfuza6rabc
> Thread support2

- matterircd.toml.example
- mm-go-irckit/server_commands.go
- mm-go-irckit/userbridge.go
Per https://github.com/42wim/matterircd/pull/344#issuecomment-733971333, this adds an option, ThreadContext="mattermost", to show the Mattermost's internal message or parent thread ID rather than the matterircd generated 3-letter hexadecimal counter (the default).
This can be used to reply to threads or create threads replying to messages.
With SuffixContext:
|19:33 <hloeung> added reaction: coffee [@@mbqq5nsgm3ypmx5befzm5y4bgh]
|19:34 <hloeung> :coffee: [@@zyo6u9ew1jgo5jnj85erxruakc]
With PrefixContext:
|19:39 <hloeung> [@@3u9tojwo1ib89j7m39riykjy3a] Test
|19:39 <hloeung> [@@mbqq5nsgm3ypmx5befzm5y4bgh] added reaction: 100
> Allow showing parent thread or message ID with PrefixContext / SuffixContext

- mm-go-irckit/userbridge.go
If ThreadContext is set, but neither PrefixContext or SuffixContext, then no replay messages.
> Fix missing replay when ThreadContext set but not PrefixContext/SuffixContext

- bridge/mattermost/mattermost.go
With ShortenRepliesTo, we can now control length of replies to
display. It can be useful even with PrefixContext/SuffixContext
enabled.
> Allow showing replies with Prefix/SuffixContext

- mm-go-irckit/server_commands.go
- mm-go-irckit/userbridge.go
- prefixcontext.md
Store the Mattermost message ID of the most recent message sent to channel. With that, we can use 'last' to modify or delete. e.g.
|21:15 <hloeung> Test
|21:15 <hloeung> s//Update last test message
|21:15 <hloeung> s//
Also add support for modifying messages using the Mattermost message ID. e.g.
|21:14 <hloeung> Test [@@o5ctj8u3qfgtxf5icisewtdyty]
|21:14 <hloeung> s/o5ctj8u3qfgtxf5icisewtdyty/Update
|21:14 <hloeung> Update (edited) [@@o5ctj8u3qfgtxf5icisewtdyty]
|21:14 <hloeung> s/o5ctj8u3qfgtxf5icisewtdyty/
|21:14 <hloeung> Update (deleted) [@@o5ctj8u3qfgtxf5icisewtdyty]
> Allow modifying or deleting last message and by Mattermost message ID

- mm-go-irckit/userbridge.go
- pkg/matterclient/matterclient.go
Per https://github.com/42wim/matterircd/issues/245, we can't trust that Mattermost has updated the last viewed for channel. Instead, we save this locally and use that for replaying of logs. Useful for when experiencing flaky network causing matterircd to reconnect.
This is also part of https://github.com/42wim/matterircd/issues/313, we can dump this out to disk and read/load on start up.
With testing on my laptop, suspend, then resume. Adding print logging on line 555 (`logger.Info("Using last saved for channel %s ", brchannel.ID, lastViewedAt)`):
[0194] ERROR matterclient: connection not alive: NewWebSocketClient: model.websocket_client.connect_fail.app_error, read tcp 192.168.1.23:42334->xxx.xxx.xxx.xxx:443: read: connection reset by peer
[0204] ERROR matterclient: got a listen error: …
> Save last viewed at state and use for replaying logs

- bridge/mattermost/mattermost.go
- bridge/slack/slack.go
- pkg/matterclient/matterclient.go
Some lines are logged without timestamps. e.g.
INFO[2020-12-25T04:27:05Z] Running version 0.21.1-dev                    module=matterircd
INFO[2020-12-25T04:27:05Z] WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.  module=matterircd
INFO[2020-12-25T04:27:05Z] Listening on 127.0.0.1:6697                   module=matterircd
INFO[2020-12-25T04:28:01Z] New connection: 127.0.0.1:52986               module=matterircd
...
loggerlevel: info
INFO[0066] login as hloeung (team: myteam) on mychat.mydomain
[0066]  INFO matterclient: Found version 5.27.0.5.27.0.3bd4fc983a4aa622183c3bd1e77029e0.true
[0070]  INFO matterclient: found 1111 users in team myteam
INFO[0072] login succeeded
This makes it so the login lines as well as matterclient also log timestamp:
loggerlevel: info …
> Logging with timestamp

- bridge/mattermost/mattermost.go
- matterircd.toml.example
Useful for when you don't want channels to be marked as seen so you can view them on another device but at the same time, you want to be seen as not idling.
> Allow forcing anti-idle

- .gitignore
- main.go
- matterircd.toml.example
- mm-go-irckit/server_commands.go
- mm-go-irckit/userbridge.go
This ensures we only replay backlog for what we haven't seen.
It is not enabled by default and only enabled when something like this is added to mattermost.toml:
LastViewedSavePath = "matterircd-lastsaved.db"
> Save lastViewedAt and load on start up (#313)

- mm-go-irckit/userbridge.go
We don't want to replay messages using lastViewedAt as that includes
the last one we've seen.
Make the 'Replaying since" messages in bold so it's clear and easy to
see when.
> Replay only messages not seen; also make it clear when replaying

- mm-go-irckit/userbridge.go
GetPostsSince will return older messages with reaction changes since LastViewedAt (query looks to be using the posts' update_at. This may be confusing as the user may think it's a duplicate, or a post out of order. Plus, we currently don't show reaction changes when relaying messages/logs so let's skip these. e.g.
$ curl -i -H 'Authorization: Bearer some-token' 'https://mychat.internal/api/v4/channels/channel_id/posts?since=1611354473840'; echo
HTTP/2 200
server: openresty/1.15.8.2
date: Sat, 23 Jan 2021 21:21:37 GMT
content-type: application/json
content-length: 1252
vary: Accept-Encoding
strict-transport-security: max-age=15724800; includeSubDomains
expires: 0
vary: Accept-Encoding
x-request-id: hm9ny96yh3...dga
x-version-id: 5.29.0.5.29.0.88ed32c9aea1c37a5f3b7d9af1b55e24.true …
> Skip already seen messages when replaying

- mm-go-irckit/userbridge.go
The nick sanitizing code missed a spot; if a nick with spaces in it sends a message on Slack, the PRIVMSG sent over IRC is malformed.
> Sanitize nick before sending PRIVMSG irc command

- mm-go-irckit/userbridge.go
Useful for those using IRC bouncers such as bip and znc to debug issues with replaying. E.g. if matterircd is replaying the same messages over and over or if it's the bouncer doing so.
> Add logging when replaying logs

- bridge/mattermost/mattermost.go
- bridge/slack/slack.go
- mm-go-irckit/commands.go
- mm-go-irckit/server.go
- mm-go-irckit/server_commands.go
- mm-go-irckit/userbridge.go
- pkg/matterclient/matterclient.go
That's the following:
$ golangci-lint run
WARN [runner] Can't process result by diff processor: can't prepare diff by revgrep: no version control repository found
mm-go-irckit/server_commands.go:584: 584-606 lines are duplicate of `mm-go-irckit/server_commands.go:608-630` (dupl)
func threadMsgChannel(u *User, msg *irc.Message, channelID string) bool {
threadID, text := parseThreadID(u, msg, channelID)
if threadID == "" {
return false
}
msgID, err := u.br.MsgChannelThread(channelID, threadID, text)
if err != nil {
u.MsgSpoofUser(u, u.br.Protocol(), "msg: "+text+" could not be send: "+err.Error())
return false
}
u.msgLastMutex.Lock()
defer u.msgLastMutex.Unlock()
u.msgLast[channelID] = [2]string{msgID, threadID}
u.saveLastViewedAt(channelID)
if u.v.GetBool(u.br.Protocol()+".prefixcontext") …
> Fix golangci-lint dupl, unused, nestif, and gocritic

- mm-go-irckit/userbridge.go
This change is needed for matrix bridge and also makes more sense.
> Handle events after initialization use buffered channel

- bridge/bridge.go
- bridge/mattermost/mattermost.go
- bridge/slack/slack.go
- mm-go-irckit/server_commands.go
This is to specific posts/messages, using the same syntax as you would via the Mattermost UI (+:emoji_name: and -:emoji_name:).
|20:22 <hloeung> @@e9jdm8qwxtdq88nb949i6tcp6y +:coffee:
|20:22 <hloeung> added reaction: coffee [↪@@e9jdm8qwxtdq88nb949i6tcp6y]
|20:22 <hloeung> @@e9jdm8qwxtdq88nb949i6tcp6y -:coffee:
|20:22 <hloeung> removed reaction: coffee [↪@@e9jdm8qwxtdq88nb949i6tcp6y]
One for you @devec0 but too late ;)
> Allow adding or removing reactions

- mm-go-irckit/user.go
Split out from https://github.com/42wim/matterircd/pull/386
So you can add multiple reactions in sequence, especially with a high PasteBufferTimeout. This also allows replying to threads or modifying messages in sequence without the chance it'll be sent as-is. e.g.
Test
s//
Two
Will delete the message `Test` and send `Two` rather than send all 3 lines with `s//` sent as text.
> Flush buffers on reactions, allows adding various reactions in sequence, also replies to threads or message modifications

- mm-go-irckit/server_commands.go
This was introduced in commit c68410c5 where threadMsgUser() now calls
threadMsgChannel() which then incorrectly calls u.br.MsgChannelThread().
msg: Test could not be send: You do not have the appropriate permissions.,
Apologies for introducing this bug.
> Fix permissions issues when replying to threads in DM

- mm-go-irckit/userbridge.go
Makes it easier to double-tap to highlight the entire URL. e.g.
|15:35 <@tuser> download file -https://mattermost.mydomain.com/api/v4/files/4a48t18bkb8rpnro88z7nys3ea
Double-tap selection includes the hyphen/dash.
> Space separate 'download file'

- mm-go-irckit/user.go
Bug introduced in commit bc88bb1. Flushing of buffers would happen when text contains '/' anywhere, and not just at the start for actions.
> Fixed buffer flushing

- mm-go-irckit/service.go
- mm-go-irckit/userbridge.go
Rather than show as being from the "mattermost" user or in the "mattermost" query window, this shows scrollback text in the same window as the one we're requesting scrollback for. Fixes https://github.com/42wim/matterircd/issues/391
> Show scrollback in same channel/query window

- bridge/bridge.go
- bridge/mattermost/mattermost.go
- mm-go-irckit/service.go
- mm-go-irckit/userbridge.go
This allows replying to or adding reactions.
Builds on and depends on #393
> Show Mattermost message/thread IDs for file attachments

- mm-go-irckit/userbridge.go
Currently the code creates the following IRC raw message (direct message sent from "buddy", to "me"):
> :buddy!buddy@https://chat.example.com PRIVMSG buddy :hi
However, according to the IRC spec rfc1459 4.4.1 (https://tools.ietf.org/html/rfc1459), direct messages should have my username set as the receiver.
i.e.
> :buddy!buddy@https://chat.example.com PRIVMSG me :hi
Fixes: #406
This code has been tested and confirmed to be working on v0.23
Thanks to @hloeung for helping verify the patch works.
> Set correct IRC PRIVMSG nick when receiving direct messages

- bridge/bridge.go
- bridge/mattermost/mattermost.go
- mm-go-irckit/userbridge.go
Basically by showing the message emoji reactions was added to or removed from.
|21:39 <hloeung> added reaction: smile (re @hloeung: Reply)
|21:39 <hloeung> added reaction: +1 (re @hloeung: Test test test test test …) [↪@@pojqjum49p8bfmizfosr8g8f8c]
|21:49 <hloeung> removed reaction: +1 (re @hloeung: Test) [↪@@aewp114y1tn55j6ahccd8qowca]
Also tested with non-mattermost message/thread IDs (so matterircd style 000-fff):
|21:59 <hloeung> added reaction: +1 (re @hloeung: Test) [001]
|22:00 <hloeung> @@001 +:thumbsup:
|22:00 <hloeung> added reaction: thumbsup (re @hloeung: Test) [001]
> Add context for reactions

- mm-go-irckit/userbridge.go
@axinojolais ran into this issue where matterircd crashed with SIGSEGV:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46cd00]
goroutine 50 [running]:
github.com/42wim/matterircd/mm-go-irckit.(*User).handleReactionEvent(0xc0000b09a0, 0x4c7820, 0xc0002c0960)
/home/matterircd/go/src/github.com/42wim/matterircd/mm-go-irckit/userbridge.go:370 +0x360
github.com/42wim/matterircd/mm-go-irckit.(*User).handleEventChan(0xc0000b09a0)
/home/matterircd/go/src/github.com/42wim/matterircd/mm-go-irckit/userbridge.go:95 +0x17e
created by github.com/42wim/matterircd/mm-go-irckit.(*User).loginTo
/home/matterircd/go/src/github.com/42wim/matterircd/mm-go-irckit/userbridge.go:814 +0x1b4
Not sure what triggered it, but this …
> Handle SIGSEGV nil pointer for event.ParentUser

- mm-go-irckit/user.go
Yet another fix to bug introduced by commit bc88bb1. Still an issue with pasting paths causing the buffers to be flushed when it shouldn't (e.g. /srv/mydir). Instead, split it into two regexs to avoid confusion. One for replies to message/threads as well as reactions and the other for message modifications.
> Fix buffer flushing yet again

- bridge/mattermost/mattermost.go
- matterircd.toml.example
Fixes https://github.com/42wim/matterircd/issues/416
We fix it so only if the message contains channel mentions @{here,channel,all} rather than if the parent message:
|21:37 -hloeung:#haw-test- @here Testing again [@@4f7tqoranpgd9bb98itfxt87qw]
|21:37 <hloeung> This time replying, which shouldn't be an IRC NOTICE message but rather PRIVMSG (re @hloeung: @here Testing again) [↪@@4f7tqoranpgd9bb98itfxt87qw]
Also adds an option to allow disabling channel wide mentions. When enabled:
|20:40 <hloeung> @here test [@@18qrfrwa9prk7y9hew49dtahio]
When disabled, which is the current behavior:
|20:41 -hloeung:#haw-test- @here test [@@18qrfrwa9prk7y9hew49dtahio]
> Fix channel mentions and add option to disable channel mentions as IRC NOTICEs

- bridge/slack/slack.go
When message is POSTed Slack will reply with message ID (basically a timestamp). Keep track of them in msgLast (similar to mm-go-irckit) and check for own messages when receiving events from Slack. Then we can drop callback id in blocks (which fixes #341)
Also sets parse=full which makes mentions work again. I think Slack changed default some time ago.
> Save message IDs and use them for local echo prevention

- mm-go-irckit/userbridge.go
Reported by @furai on IRC. This is due to having two event chan readers.
> Fix ordering of events (such as code blocks)

- mm-go-irckit/userbridge.go
Useful for when you want to restart matterircd and not have any logs replayed. To flush or force saving of last viewed at state, use the `logout` command per below:
/msg mattermost logout
We also want to make sure we use the server's known channel last viewed if it's newer than what's saved to further reduce messages we've `seen`.
> Save last viewed at state on logout and only use stored last viewed at if newer than what the server knows

- mm-go-irckit/userbridge.go
Mainly for https://github.com/42wim/matterircd/issues/421#issuecomment-810634715 where the warning about not being able to load the lastViewedAt state file can be confusing when it doesn't currently exist.
> Don't show warning if lastViewedAt state file doesn't exist, also create it early

- mm-go-irckit/userbridge.go
28/04 21:23 < bob> something something please ?
28/04 21:23 < bob> @@!! actually, 2s
28/04 21:23 <@stuart> [↪rjjmk…] added reaction: waiting (re @bob: actually, 2s …)
28/04 21:23 <@stuart> [↪rjjmk…] removed reaction: waiting (re @stuart: actually, 2s …)
The "removed reaction" shows the incorrect user/nick of the message the reaction was made to (or removed from). Instead of stuart, it should have been bob just like the reaction add line before it.
> Fix incorrect nick for reaction removal

- bridge/mattermost/mattermost.go
- mm-go-irckit/channel.go
- mm-go-irckit/service.go
- mm-go-irckit/userbridge.go
This fixes https://github.com/42wim/matterircd/issues/420
```
Test
Test 2 indent
Test 3 indent again
```
Becomes:
|23:49 <hloeung> ``` [q53f6qrotfremdiwc6bt1f891c]
|23:49 <hloeung> Test [q53f6qrotfremdiwc6bt1f891c]
|23:49 <hloeung> Test 2 indent [q53f6qrotfremdiwc6bt1f891c]
|23:49 <hloeung> Test 3 indent again [q53f6qrotfremdiwc6bt1f891c]
|23:49 <hloeung> ``` [q53f6qrotfremdiwc6bt1f891c]
Instead, we want to preserve indentation / leading whitespace as well as new lines so with PrefixContext, it will look as follows:
|00:10 <hloeung> [obg5jhw51byafg1uapjp4883we] ```
|00:10 <hloeung> [obg5jhw51byafg1uapjp4883we] Test
|00:10 <hloeung> [obg5jhw51byafg1uapjp4883we]
|00:10 <hloeung> [obg5jhw51byafg1uapjp4883we]     Test 2 indent
|00:10 <hloeung> [obg5jhw51byafg1uapjp4883we]
|00:10 <hloeung> …
```
> Preserve leading whitespace and for code blocks, new/empty lines. Fixes #420

- mm-go-irckit/server.go
Newer versions of the IRC protocol support a message called CAP to negotiate capabilities, what the server can and cannot do
In order to implement this properly, the newest version of irssi (currently unreleased) sends out a JOIN command in order to see if the server has properly replied to the CAP message or not.
Since matterircd is the only ircd not responding with an error to this join message, irssi cannot connect to matterircd anymore. Instead the connection times out.
This patch fixes this by ensuring the join message returns an error if tried before the registration is complete
> Return ERR_NOTREGISTERED when trying to join before registration

- mm-go-irckit/userbridge.go
This should fix any unordered messages, but no idea why they are
unordered in the first place...
> Use unbuffered eventChan for slack/mattermost. Fixes #426

- matterircd.toml.example
- mm-go-irckit/server.go
Just as the title says, allow overriding the default 10seconds handshake timeout - https://github.com/42wim/matterircd/issues/438
> Allow overriding handshake timeout. Fixes #438

- bridge/slack/slack.go
I just ran into this bug
```
slack-go/slack2021/06/15 13:33:02 websocket_managed_conn.go:387: Incoming Event: {"type":"message","subtype":"bot_message","text":"","suppress_notification":false,"bot_id":"B0A4JCWSK",...
2021/06/15 13:33:02 protocol error: received *http.http2GoAwayFrame before a SETTINGS frame
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8705f9]
goroutine 291 [running]:
github.com/42wim/matterircd/bridge/slack.(*Slack).getSlackUserFromMessage(0xc0000a2600, 0xc0006f4000, 0x9e6c0b, 0x29, 0xc0002f53f0)
/home/akolehma/go/src/github.com/42wim/matterircd/bridge/slack/slack.go:681 +0x2f9
github.com/42wim/matterircd/bridge/slack.(*Slack).handleSlackActionPost(0xc0000a2600, 0xc0006f4000) …
```
> Fix segfault when bot user fetch fails

- bridge/mattermost/mattermost.go
- matterircd.toml.example
- mm-go-irckit/server.go
- pkg/matterclient/matterclient.go
I want to be able to check messages I haven't read in the Town Square on a different device, but at the same time, have the anti-idle feature on. I have a separate test channel to use for anti-idling.
Since we're here, also allow overriding the anti-idle interval.
> Allow overriding the anti-idle channel and interval

- bridge/mattermost/mattermost.go
- mm-go-irckit/service.go
- mm-go-irckit/userbridge.go
Rather than this:
|14:07 <myuser> myuser removed from the team.
We get this:
|14:07 <system> myuser removed from the team.
This better matches with what's shown via the Mattermost web UI:
System 00:23
@myuser was removed from the team.
As well as when users are added or removed from channels per https://github.com/42wim/matterircd/blob/master/mm-go-irckit/userbridge.go#L187 :
|00:56 <system> added myuser to the channel by hloeung
> Addition and removal of user to/from team from system

- mm-go-irckit/server_commands.go
|07:34 <hloeung> msg: Test disconnection could not be sendhttps://mymattermostserver.local/api/v4/posts: ...
Becomes:
|07:34 <hloeung> msg: Test disconnection could not be sent https://mymattermostserver.local/api/v4/posts: ...
> Fix word boundary and grammar of error messages

- bridge/mattermost/mattermost.go
Sometimes, we'll end up with messages with additional line breaks then the reply msg is added but on a separate line. This fixes that so it's always on the same line as the last line of the message.
> Fix to ensure reply message is on the same line as last message line

- bridge/mattermost/mattermost.go
- matterircd.toml.example
- pkg/matterclient/matterclient.go
Increasing this reduces duplicate messages or errors about not finding
parent thread ID in time when either Mattermost server is under heavy
or slow client connection to the Mattermost server.
> Allow overriding client timeout

- vendor/github.com/matterbridge/matterclient/matterclient.go
Fixes #457 
This panic shows that `resp` can be nil, which is strange to get an nil response here. 
Return an error now.
> Fix possible panic in mattermost

- matterircd.service
Haven't found systemd unit next to Dockerfile and thought that maybe one will be useful in the repository.
Not sure if maybe this is deliberately left up to distros, but given that releases supply simple binaries, maybe useful to have for people who use those in some systemd-enabled env (most linux distros, incl. in VMs or nspawn/lxc containers).
This unit sets up everything-readonly-but-one-homedir container (DynamicUser=yes implies most of it).
With static Go binary, it might also be possible to configure something simplier like TemporaryFileSystem=/ + BindReadOnlyPaths='/proc /usr/bin/matterircd:/matterircd' to basically get same thing as Docker container in fs namespace, but dunno if daemon might still need libc and its stuff in /etc with some builds.
Since extremely verbose and …
> Add systemd service unit example

- mm-go-irckit/server_commands.go
With commit 4215119a0722506cb43fa2331619b683de05efb4, when replying to threads with a multi-line post such as:
```
Test 1
Test 2
Test 3
```
Only the first line is used, so the message becomes just:
```
This fixes that.
> Fix multiline replies to threads

- bridge/mattermost/mattermost.go
- bridge/mattermost6/mattermost.go
- matterircd.toml.example
- mm-go-irckit/channel.go
- mm-go-irckit/service.go
- mm-go-irckit/userbridge.go
With the new no splitting multi-line messages in PR #482, multi-line messages are displayed as:
```
|20:09 <hloeung> Test One
|20:09 <hloeung> Test Two
|20:09 <hloeung> Test Three [c9ouoenfkprajc6o96zdp9z87y]
|20:16 <hloeung> Test One
|20:16 <hloeung> Test Two
|20:16 <hloeung> Test Three (re @hloeung: Test One Test Two Test …) [↪c9ouoenfkprajc6o96zdp9z87y,ak8gwopx4jnqbjf5ipnrtifyrc]
```
Unfortunately, it means using tools such as grepping won't show all the lines as part of the message. This fixes that:
```
|20:48 <hloeung> Test One [↪c9ouoenfkprajc6o96zdp9z87y,6wfxbuie3ty8x84ya4fpj8cabr]
|20:48 <hloeung> Test Two [↪c9ouoenfkprajc6o96zdp9z87y,6wfxbuie3ty8x84ya4fpj8cabr]
|20:48 <hloeung> Test Three (re @hloeung: Test One Test Two Test …) …
```
> Ensure prefixcontext/suffixcontent shown for all lines in a multi-line message

- bridge/mattermost/mattermost.go
- bridge/mattermost6/mattermost.go
- matterircd.toml.example
- mm-go-irckit/channel.go
- mm-go-irckit/service.go
- mm-go-irckit/userbridge.go
This fixes https://github.com/42wim/matterircd/issues/480 and as a bonus also fixes https://github.com/42wim/matterircd/issues/426 as this is now just 1 big message for irc
> Do not split message on newlines

- bridge/mattermost/mattermost.go
- bridge/mattermost6/mattermost.go
- mm-go-irckit/server.go
We only need to call this for when channels and user changes. This fixes #492.
> Reduce UpdateChannelsTeam() calls

- bridge/mattermost6/mattermost.go
- mm-go-irckit/userbridge.go
Fixes https://github.com/42wim/matterircd/issues/479
> Fallback to use API for getting channel data when not in the cache

- mm-go-irckit/userbridge.go
See https://github.com/42wim/matterircd/issues/461.
> Fix "key required" crash when channel ID can't be found

- mm-go-irckit/userbridge.go
An action with less than the length of prefix gets split on multiple lines and causes "unknown CTCP ACTION".
```
|20:44 hloeung [hloeung@hloeung] requested unknown CTCP ACTION from #haw-test:
|20:44 <hloeung> [@@935mkzt8h3ggxmdsrqpyq45j3o]
|20:44 <hloeung> Testing A
```
> Fix splitting of lines for ACTIONs

- mm-go-irckit/userbridge.go
That is:
```
Testing
` ` ` go
package main
import "fmt"
func main() {
fmt.Println("Hello, 世界")
}
` ` `
Testing end
```
Becomes:
```
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao] Testing
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao] ``` go
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao] package main
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao]
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao] import "fmt"
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao]
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao] func main() {
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao]     fmt.Println("Hello, 世界")
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao] }
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao] ```
|14:24 <hloeung> [@@pwxztbmprbgim8hsa5j9147jao] Testing end
```
That is, empty lines are …
> Support for empty lines in syntax highlighted code blocks

- bridge/mastodon/mastodon.go
- mm-go-irckit/userbridge.go
Also removes the irc joins
And uses the | as in the nick as the `user|host` because `user@host` isn't a valid irc nick
> Add support for posting on timeline (mastodon)

- mm-go-irckit/userbridge.go
Otherwise, we end up bouncing between being marked away and not.
Mostly seems to happen when visiting via the web UI, at least that's how I used it to reproduce it.
```
|18:29 -!- You are no longer marked as being away
|18:32 -!- You have been marked as being away
|18:32 -!- You are no longer marked as being away
|18:32 -!- Irssi: No new messages in awaylog
|18:35 -!- You have been marked as being away
|18:35 -!- You are no longer marked as being away
|18:35 -!- Irssi: No new messages in awaylog
|18:37 -!- You have been marked as being away
|18:37 -!- You have been marked as being away
```
Then with additional debug logging, we can see the states:
```
ERRO[2022-11-14T18:29:45+11:00] HAW handleStatusChangeEvent(): online
ERRO[2022-11-14T18:29:45+11:00] HAW server status online …
```
> Ignore when our user status is "offline"

- README.md
While looking at the docs on how to set up multiple Mattermost servers, found that we still have references to freenode IRC.
> Update docs, moved from freenode IRC to Libera Chat

- mm-go-irckit/userbridge.go
As pointed out by Furai on IRC, Mattermost supports tilde fenced code blocks so we should support it too, see https://www.markdownguide.org/extended-syntax/#fenced-code-blocks.
> Add support for tilde fenced code blocks

- mm-go-irckit/server_commands.go
This fixes and suppresses these error messages:
```
ERRO[2022-11-16T18:42:28Z] Cannot join channel &users, id , err: cannot join channel (+i)  module=matterircd
ERRO[2022-11-16T18:42:29Z] Cannot join channel &messages, id , err: cannot join channel (+i)  module=matterircd
```
> Ignore special channels

- bridge/mattermost/mattermost.go
There is this extra and unnecessary API GET call to the Mattermost server for files links (`/files/*/link`). Messages with attached files is already handled in `handleFileEvent()` so no need for in `handleWsActionPost()`.
> Reduce extra call to Mattermost server for files link

- mm-go-irckit/channel.go
- mm-go-irckit/server_commands.go
Remove calls to set/update topics on joining and other users joining channels.
This causes the whole topic set by yourself in IRC for some channels.
> Remove unnecessary topic setting on channel join

- mm-go-irckit/channel.go
- mm-go-irckit/userbridge.go
This fixes #[516](https://github.com/42wim/matterircd/issues/516) which was caused by the removal of new lines per commit 2ddb0d4.
> Ensure colon present for empty messages per IRC protocol/spec

- bridge/mattermost/mattermost.go
- mm-go-irckit/userbridge.go
Replaces https://github.com/42wim/matterircd/pull/508. For each message that's a reply to a thread, we make an extra API call to get the parent message to use as reply text. This caches that to reduce requests to the MM server.
> Reduce calls to Mattermost server by caching replies

- bridge/mattermost/mattermost.go
When replies are accidentally using the post IDs for those part of threads or reactions, we end up with an error:
```
msg: ... could not be sent : Invalid RootId parameter.,
```
This better handles that by trying to get the post and following the parent/root ID of that.
So given the following:
```
|23:52 <wuser1> my reply message (re @suser2: my parent message …)
[@@hfe4hxb13pr59xf6fs5qfdrquh,gw4zu7kmji8r3byk4qer1dx7xa]
```
One can reply with either the msg thread/parent/root ID of `@@hfe4hxb13pr59xf6fs5qfdrquh` or using the actual post ID, `@@gw4zu7kmji8r3byk4qer1dx7xa`.
It's also useful for reactions too which we're only showing the post ID (will work on a separate PR to show the thread/parent/root ID for reactions too).
> Handle replies to posts part of threads

- bridge/mattermost/mattermost.go
- bridge/slack/slack.go
- bridge/slack/utils.go
- main.go
- mm-go-irckit/user.go
I like to think it's an improvement.
Rather than append "module=matterircd" and such, have the module prefixed much like what's used by matterclient. Also split out what's logged by the main matterircd or the bridges (mattermost & slack).
```
[2022-11-19T22:19:20Z] DEBUG matterclient: found 162 channels for user in team ...
[2022-11-19T22:19:20Z] DEBUG matterclient: found 1333 public channels in team ...
[2022-11-19T22:19:20Z] DEBUG matterclient: WsClient: making connection: wss://myserver.mydomain.local
[2022-11-19T22:19:21Z] DEBUG matterclient: WsClient: connected
[2022-11-19T22:19:21Z] DEBUG matterclient: starting wsreceiver
[2022-11-19T22:19:21Z] DEBUG matterclient: executing OnWsConnect()
[2022-11-19T22:19:21Z] DEBUG matterircd: bridge not ready yet, sleeping
[2022-11-19T22:19:21Z] …
```
> Improve on logging and make consistent with matterclient

- bridge/bridge.go
- bridge/mastodon/mastodon.go
- bridge/mattermost/mattermost.go
- bridge/slack/slack.go
- mm-go-irckit/service.go
Mainly useful for seeing what your last replies/posts were, especially when using `@@!!`.
```
|21:17 <hloeung> lastsent
|21:17 <mattermost> [@@jz6umt46w38spqcjppox6kk7ky] user1: my first message
|21:17 <mattermost> [@@ndziyrp7pig7zrsf643qiwe97a] #haw-test: Testing
|21:17 <mattermost> [@@zajoh97ms7f8jyyq1j3iu4nudr] user1: ok (re @user1: Here …)
```
> Cache last sent msgs

- bridge/mattermost/mattermost.go
Testing:
```
|17:33 <hloeung> Testing (re @hloeung: Testing my edited message …) [↪1hfz…,xbku…]
|17:33 <hloeung> Test message (edited) [1hfz…]
|17:34 <hloeung> Testing (re @hloeung: Test message) [↪1hfz…,f676…]
|17:34 <hloeung> Testing, reply (re @hloeung: Test message) [↪1hfz…,yegh…]
|17:34 <hloeung> Testing, updated message (edited) [1hfz…]
|17:34 <hloeung> Testing, reply after parent updated (re @hloeung: Testing, updated message …) [↪1hfz…,1soj…]
```
Without it, if the original/parent message has been edited/updated, all replies will show the old message.
> Evict cached msg on edit/delete to ensure replies don't use stale/old msgs

- matterircd.toml.example
- mm-go-irckit/userbridge.go
This makes it a little bit more future proof by allowing the admin/user to select ignore supported Mattermost server version and **use at own risk** per https://github.com/42wim/matterircd/issues/537
> Allow ignoring Mattermost server version when checking if supported

- mm-go-irckit/server_commands.go
- mm-go-irckit/service.go
- mm-go-irckit/userbridge.go
That way, we can tell where prefixContext() is being called from
> Add missing event to prefixContext() calls for easier debugging

- mm-go-irckit/server_commands.go
- mm-go-irckit/userbridge.go
When using mattericd's default threading, the msgMap is populated with message/thread IDs and never removed. This means that when we cycle past 4k, we can have entries with duplicate counters causing issues where replies could end up to an incorrect thread.
This fixes it by introducing an index with the counter and to which message/thread ID. When index entries are updated and the thread no longer referenced, the entries in the msgMap are removed.
This also ensures that msgMap remains a constant bounded size.
It should be noted that this also relies on https://github.com/42wim/matterircd/pull/544, in particular https://github.com/42wim/matterircd/blob/master/mm-go-irckit/server_commands.go#L665
> Fix incorrect msg/thread counters

- bridge/mattermost/mattermost.go
- mm-go-irckit/server_commands.go
- mm-go-irckit/user.go
From https://stackoverflow.com/questions/56678124/how-to-cache-the-compiled-regex-in-go
> Use static initialisation for regular expressions to optimize

- matterircd.toml.example
- mm-go-irckit/userbridge.go
Do the reverse of https://github.com/42wim/matterircd/pull/546 for https://github.com/42wim/matterircd/issues/258, convert Mattermost posts with markdown formatting / emphasis to IRC. Example:
Testing **Bold** Testing **_Bold+Italics_** Testing _Italics_ Testing `monospace` Testing
Becomes:
(FWIW, monospace support was added in irssi 1.4.4, I'm running 1.4.3 and why it's showing as `Q`)
> Convert Mattermost markdown formatting / emphasis to IRC

- mm-go-irckit/userbridge.go
This fixes https://github.com/42wim/matterircd/issues/561
If NotifyProps["mention_keys"] (aka "Words That Trigger Mentions") is empty, `strings.Split(mentionkeys, ",")` creates a slice with one element, the empty string - `[]string{""}` rather than an empty slice (`[]string{}`). This causes all lines to match.
We can handle it at the `strings.Split()`, or around it. But I thought best to handle it in the loop in case the user does something like `test1,test2,,test3` where there is an accidental comma.
> Fix mentions for every message

- mm-go-irckit/userbridge.go
Following up on https://github.com/42wim/matterircd/pull/563 where file events for non-joined channels are still showing rather than going to &messages.
> Add option to only show messages in joined channels for file events also

- mm-go-irckit/userbridge.go
We only call getMessageChannel() when .showonlyjoined and it's not a direct message. getMessageChannel() creates a channel in IRC.
Fixes #571
> Fix channels created for file events via DM

- mm-go-irckit/userbridge.go
This is  a simple patch that enables support for Mattermost 10.
Closes  #584
> Support Mattermost 10.0.0
