42wim/matterircd

main.go
=> Make binding interface configurable

README.md
* Minor changes to the formatting
* Clarifications about the `/msg mattermost LOGIN command`
=> Add information about docker image at Docker Hub

.gitignore, config/config.go, main.go, matterircd.toml.example
=> Add config file option.

main.go, mm-go-irckit/LICENSE, mm-go-irckit/README.md, mm-go-irckit/channel.go, mm-go-irckit/commands.go, mm-go-irckit/logger.go, mm-go-irckit/mmchannel.go, mm-go-irckit/mmserver.go, mm-go-irckit/mmservice.go, mm-go-irckit/mmservice_test.go, mm-go-irckit/mmuser.go, mm-go-irckit/net.go, mm-go-irckit/server.go, mm-go-irckit/server_commands.go, mm-go-irckit/server_test.go, mm-go-irckit/slackuser.go, mm-go-irckit/user.go, mm-go-irckit/user_test.go, mm-go-irckit/utils.go
Integrate github.com/42wim/mm-go-irckit into matterircd
=> Integrate mm-go-irckit into matterircd

config/config.go, matterircd.toml.example, mm-go-irckit/mmuser.go
This fixes #225.
My initial tests shows that this is working properly. Let me know if I should make any adjustments.
=> Added support for disabling of automatic view flag updates

mm-go-irckit/slackuser.go
Some small tweaks on how slack messages are shown in IRC
* Mark thread replies with [T time] prefix
* Show text always from all attachments
* Show uploaded file name/type/link
* Show raw message if nothing else can be shown
* Slackbot added to all channels so its messages can be shown in channel
```
12:19:27 < Aketzu> test file
12:19:27 < Aketzu> Uploaded hosted image.png / Pasted image at 2019-02-23, 12:19 PM
(png): https://files.slack.com/files-pri/zzzzz/image.png
12:19:42 < Aketzu> [T 12:19:27] so very files
```
=> Message showing enhancements

mm-go-irckit/slackuser.go
Message edits show up as
```
22:47:01 < Aketzu> foo
22:47:05 < Aketzu> [C 22:47:01] foobar
```
and deletions
```
22:47:10 < slackbot> [M 22:47:01] Message deleted
```
=> Handle message edits and deletion

mm-go-irckit/mmuser.go
Fix @all so it's an IRC notice much like @here.
=> Added support for @all

bridge/slack/slack.go
=> Create a fake user when getting a bot_message (slack)

pkg/matterclient/matterclient.go
=> Fix nil User when using tokens (mattermost)

mm-go-irckit/server_commands.go
=> Ignore empty channels and non-channels for TOPIC

mm-go-irckit/userbridge.go
=> Use override_username when available in backlog

README.md, bridge/bridge.go, bridge/mattermost/mattermost.go, mm-go-irckit/service.go, pkg/matterclient/matterclient.go
This is a first implementation into trying to support second factor authentication with matterircd connecting to a mattermost server.
Fixes #272  #261
=> feat(2fa): supports 2fa authentication

pkg/matterclient/matterclient.go
This fixes https://github.com/42wim/matterircd/issues/359
=> Fixed logging in with personal access token

mm-go-irckit/server_commands.go, mm-go-irckit/userbridge.go
Continuation of https://github.com/42wim/matterircd/pull/362
On IRC:
Which then produces the following via the Mattermost web UI:
=> Allow replying to own last message which is part of a thread

mm-go-irckit/userbridge.go
|00:25 <hloeung> Test (re @hloeung: Test) [->@@bffqtoecwtbcpr3k4n1g16ty4w]
|00:35 <hloeung> Test [@@1be5y8pmxpgn5c73keywnh9c8w]
Idea or request came from @axinojolais making it easier to tell if a message is a reply to a thread. Especially if you have HideReplies set.
=> Add prefix showing messages are replies to threads when using Mattermost ThreadContext

mm-go-irckit/service.go
/msg mattermost scrollback @someuser 10
=> Add scrollback support for direct messages (DMs). Fixes #385

bridge/slack/slack.go
=> Use conversation API for DM (slack)

matterircd.toml.example, mm-go-irckit/userbridge.go
Fixes https://github.com/42wim/matterircd/issues/413
=> Add option to hide reactions; also hide our own

README.md
=> FAQ: docs for connecting to multiple servers

mm-go-irckit/server_commands.go
One of the three places where thread references are parsed did not strip the separator. Unfortunately was the path I most often took. Instead of duplicating the code again, opted to fully parse replies with a regexp.
=> strip separator when replying with short thread ID

mm-go-irckit/server.go, mm-go-irckit/server_commands.go
=> Fix RPL_MYINFO and move debuglevel output to MOTD

mm-go-irckit/server.go
This is for https://github.com/42wim/matterircd/issues/476
Testing using irssi:
```
INFO[2022-10-12T19:43:04+11:00] New connection: 127.0.0.1:54024               module=matterircd
DEBU[2022-10-12T19:43:04+11:00] using paste buffer timeout: 1000              module=matterircd
DEBU[2022-10-12T19:43:04+11:00] <- CAP LS 302                                 module=matterircd
DEBU[2022-10-12T19:43:04+11:00] <- JOIN :                                     module=matterircd
DEBU[2022-10-12T19:43:04+11:00] -> :matterircd CAP * LS :                     module=matterircd
DEBU[2022-10-12T19:43:04+11:00] <- CAP END                                    module=matterircd
DEBU[2022-10-12T19:43:04+11:00] <- NICK hloeung                               module=matterircd
```
Testing with netcat:
```
$ nc -C -v …
```
=> Add support for IRCv3 Client Capability Negotiation

mm-go-irckit/userbridge.go
It looks like we missed a change added by #425 when duplicating addUserToChannelWorker() for Mattermost 6 support in #452.
See https://github.com/42wim/matterircd/blob/master/mm-go-irckit/userbridge.go#L616
=> Fix replaying to match addUserToChannelWorker

go.mod, go.sum, vendor/github.com/matterbridge/matterclient/channels.go, vendor/github.com/matterbridge/matterclient/matterclient.go, vendor/modules.txt
=> Update matterclient vendor

bridge/mattermost6/mattermost.go
See https://github.com/42wim/matterircd/issues/414
```
|17:56 <matterpoll> hloeung: My question for my poll? [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll> * Option 1 [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll> * Option 2 [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll> --- [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll> *Total votes*: 0 [@@mf6mze5gw7ncbczrromg9jykjy]
```
Then when someone votes:
```
|17:56 <matterpoll> hloeung: My question for my poll? [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll> * Option 1 [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll> * Option 2 [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll> --- [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll> *Total votes*: 1 [@@mf6mze5gw7ncbczrromg9jykjy]
|17:56 <matterpoll>  (edited) …
```
=> Add support for the Matterpoll plugin

main.go, mm-go-irckit/userbridge.go
Followup on https://github.com/42wim/matterircd/pull/425
Should probably target this one for the 0.26.0, 0.27.0, or later milestone.
=> Persistent last viewed multi users cleanup

mm-go-irckit/channel.go, mm-go-irckit/userbridge.go
These look to be causing extra empty lines to be logged in debug log but otherwise noop from what I can tell.
=> Remove extra new lines showing in debug logging

mm-go-irckit/userbridge.go
This fixes the "You're not on that channel" messages in my IRC client every now and again when some channel is deleted that I'm not in.
=> Part only when in channel

bridge/mattermost/mattermost.go
We only skip posts/msgs sent from this instance of matterircd and show others sent from the same user from another instance.
Also useful for testing and developing matterircd where we can have multiple instances.
=> Allow multiple matterircd instances

mm-go-irckit/userbridge.go
=> Support mattermost version 8, drop support for version 6

mm-go-irckit/service.go, mm-go-irckit/userbridge.go
Also fix counters by doing the looking for all events, not just post_edited, post_deleted, or reaction.
=> Include thread context for matterircd hex numbers for replay and scrollback

mm-go-irckit/service.go, mm-go-irckit/userbridge.go
This makes it easier to tell which are system messages and reactions, IMO
=> Emphasize system and reaction messages

mm-go-irckit/service.go
So you can do things such as
/msg mattermost scrollback @@uobcncduufdw5bkpx7foqh74hc 0
Or by URL
/msg mattermost scrollback https://mychatserver.internal/myteam/pl/uobcncduufdw5bkpx7foqh74hc 0
=> Update scrollback to support @@msgthreadID and the MM postlist URL

README.md, mm-go-irckit/service.go
Fixes https://github.com/42wim/matterircd/issues/568
=> Add command to part/leave channels
